# Generated by Django 3.2.7 on 2021-09-08 19:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('type', models.CharField(choices=[('Trainer', 'Trainer'), ('Judge', 'Judge'), ('Mentor', 'Mentor')], default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/contributors')),
                ('facebook_url', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('instagram_url', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('linkedin_url', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('twitter_url', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=128)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discord_id', models.CharField(max_length=100, null=True)),
                ('discord_username', models.CharField(max_length=100, null=True)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('study_at', models.CharField(blank=True, max_length=100, null=True)),
                ('excitement', models.IntegerField()),
                ('experience', models.CharField(max_length=100)),
                ('is_leader', models.BooleanField(default=False)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
        ),
    ]
