"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os 
import django_heroku
import dj_database_url
import environ

# init env
env = environ.Env(
    SENDGRID_API_KEY=(str,""),
    SENDGRID_TEMPLATE_ID=(str,""),
    DISCORD_CLIENT_ID=(str,""),
    DISCORD_CLIENT_SECRET=(str,""),
    DISCORD_BOT_TOKEN=(str,"")
)

if "SENDGRID_API_KEY" in os.environ:
    SENDGRID_API_KEY = os.environ["SENDGRID_API_KEY"]
else:
    SENDGRID_API_KEY = env("SENDGRID_API_KEY")

if "SENDGRID_TEMPLATE_ID" in os.environ:
    SENDGRID_TEMPLATE_ID = os.environ["SENDGRID_TEMPLATE_ID"]
else:
    SENDGRID_TEMPLATE_ID = env("SENDGRID_TEMPLATE_ID")

if "DISCORD_CLIENT_ID" in os.environ:
    DISCORD_CLIENT_ID = os.environ["DISCORD_CLIENT_ID"]
else:
    DISCORD_CLIENT_ID = env("DISCORD_CLIENT_ID")

if "DISCORD_CLIENT_SECRET" in os.environ:
    DISCORD_CLIENT_SECRET = os.environ["DISCORD_CLIENT_SECRET"]
else:
    DISCORD_CLIENT_SECRET = env("DISCORD_CLIENT_SECRET")

if "DISCORD_BOT_TOKEN" in os.environ:
    DISCORD_BOT_TOKEN = os.environ["DISCORD_BOT_TOKEN"]
else:
    DISCORD_BOT_TOKEN = env("DISCORD_BOT_TOKEN")

API_ENDPOINT = 'https://discord.com/api/v8'

# SERVER ID
DISCORD_SERVER_ID = '785975037869686804'


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vwuu4eyhhfc&chgl$h!43di=)n(%a4crbg8888vo_##o&6jn4m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASE_URL = os.environ.get('DATABASE_URL')
# db_from_env = dj_database_url.config(default=DATABASE_URL, conn_max_age=500, ssl_require=True)
# DATABASES['default'].update(db_from_env)
# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
